config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  resources :restaurants do
    collection do
      get 'search'
    end
    resources :beer_reviews, except: [:show, :index]
      collection do
        get 'search'
      end
  end
  get 'pages/about'

  get 'pages/contact'

  root 'restaurants#index'

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  mount_uploader :image, ImageUploader

  searchkick
  
  has_many :beer_reviews

  validates :name, :address, :phone, :image, presence: true
  validates :phone, format: { with: /\A\(\d{3}\) \d{3}-\d{4}\z/,
  	message: "number must be formated (123) 456-7890" }
  validates :website, format: { with: /\Ahttps?:\/\/.*\z/,
  	message: "must start http:// or https://" }
  validates :address, format: { with: /\A\d+-?\d+ [^,]+, [A-Z][a-z]+, [A-Z]{2} [A-Z][0-9][A-Z] [0-9][A-Z][0-9]\z/,
  	message: "format is 1234-100 Test St, Ottawa, ON, K1K 1K1" }
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show, :search]
  before_action :check_user, except: [:index, :show, :search]


  def search
    if params[:search].present?
      @restaurants = Restaurant.search(params[:search])
    else
      @restaurants = Restaurant.all
    end
  end

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
    @beer_reviews = BeerReview.where(restaurantid: @restaurant.id).order("created_at DESC")
    if @beer_reviews.blank?
      @avg_rating = 0
    else
      @avg_rating = @beer_reviews.average(:rating).round(2)
    end
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :phone, :website, :image)
    end

    def check_user
      unless (current_user.admin?)
        redirect_to root_url, alert: "Sorry, only admins can do that!"
      end
    end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant, :html => {multipart: true}) do |f| %>
  <% if @restaurant.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h4>

      <ul>
      <% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :address %><br>
    <%= f.text_field :address, class: "form-control"  %>
  </div>
  <div class="form-group">
    <%= f.label :phone %><br>
    <%= f.text_field :phone, class: "form-control", placeholder: "(123) 456-7890"  %>
  </div>
  <div class="form-group">
    <%= f.label :website %><br>
    <%= f.text_field :website, class: "form-control"  %>
  </div>
  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control"  %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/restaurants/_jumbotron.html.erb
<div class="jumbotron">
  <h2>Welcome to the BeerMe App!</h2>
  <h3>The number one place for friends, fun, and good beer at great prices!</h3>
</div>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form' %>

<%= link_to 'Show', @restaurant, class: "btn btn-link" %> |
<%= link_to 'Back', restaurants_path, class: "btn btn-link" %>

app/views/restaurants/index.html.erb
<%= render 'restaurants/jumbotron' %>

<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Website</th>
      <% if user_signed_in? && current_user.admin? %>
        <th colspan="2"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= link_to restaurant.name, restaurant %></td>
        <td><%= link_to restaurant.address, "https://maps.google.com/maps?&q=#{restaurant.address.parameterize}", target: "_blank" %></td>
        <td><%= restaurant.phone %></td>
        <td><%= link_to restaurant.website, restaurant.website, target: "_blank" %></td>
        <% if user_signed_in? && current_user.admin? %>
          <td><%= link_to 'Edit', edit_restaurant_path(restaurant), class: "btn btn-link"  %></td>
          <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link"  %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<% if user_signed_in? && current_user.admin? %>
    <%= link_to 'New Restaurant', new_restaurant_path, class: "btn btn-link"  %>
<% end %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form' %>

<%= link_to 'Back', restaurants_path, class: "btn btn-link" %>

app/views/restaurants/search.html.erb
<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Website</th>
      <% if user_signed_in? && current_user.admin? %>
        <th colspan="2"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= link_to restaurant.name, restaurant %></td>
        <td><%= link_to restaurant.address, "https://maps.google.com/maps?&q=#{restaurant.address.parameterize}", target: "_blank" %></td>
        <td><%= restaurant.phone %></td>
        <td><%= link_to restaurant.website, restaurant.website, target: "_blank" %></td>
        <% if user_signed_in? && current_user.admin? %>
          <td><%= link_to 'Edit', edit_restaurant_path(restaurant), class: "btn btn-link"  %></td>
          <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link"  %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/restaurants/show.html.erb
<div class="row">
	<div class="col-md-3">
		<%= image_tag @restaurant.image_url %>

		<h3>
		  <strong><%= @restaurant.name %></strong>
		</h3>

		<div class="star-rating" data-score= <%= @avg_rating %> ></div>
		<p style="font-size: 8pt"><%= "#{@beer_reviews.length} Beer Reviews" %></p>

		<p>
		  <strong>Address:</strong>
		  <%= @restaurant.address %>
		</p>

		<p>
		  <strong>Phone:</strong>
		  <%= @restaurant.phone %>
		</p>

		<p>
		  <strong>Website:</strong>
		  <%= link_to @restaurant.website, @restaurant.website, class: "btn btn-link", target: "_blank" %>
		</p>
		<% if (user_signed_in?) && (current_user.admin?) %>
		    <%= link_to "Edit Restaurant", edit_restaurant_path(@restaurant) %>
		    <%= link_to "Delete Restaurant", restaurant_path(@restaurant), method: :delete %>
			<br />
		<% end %>
		<%= link_to 'New Review', new_restaurant_beer_review_path(@restaurant), class: "btn btn-primary" %>
		<br />
		<br />
		<iframe 
			width="250" 
			height="250" 
			frameborder="0" 
			style="border:0" 
			src="https://www.google.com/maps/embed/v1/place?key=AIzaSyALx2ueWjq_cPKIokhTzJiML0QhqosVuD8&q=<%= @restaurant.address.parameterize %>" 
			allowfullscreen>
		</iframe>

	</div>

	<div class="col-md-9">
		<% if @beer_reviews.blank? %>
			<h4>No Beer Reviews for this restaurant.  Be the first to let us know about the best beers they have!</h4>
		<% else %>
			<table class="table">
				<thead>
					<tr>
						<th class="col-md-3"></th>
						<th class="col-md-9"></th>
					</tr>
				</thead>
				<tbody>
					<% @beer_reviews.each do |beerreview| %> 
						<tr>
							<td>
								<h4>
									<% if beerreview.user.nil? %>
										<%= "#{beerreview.user_id}" %>
									<% else %>
										<%= "#{beerreview.user.first_name.present? ? beerreview.user.first_name.capitalize : '<missing>'}" %>
										<%= "#{beerreview.user.last_name.present? ? beerreview.user.last_name.capitalize[0] : '<missing>'}" %>
									<% end %>
								</h4>
								<p> <%= beerreview.created_at.strftime("%-m/%-d/%y %l:%M %P") %>
								</p>
								<div style="font-size: 8pt">
									<% if user_signed_in? %>
									  <% if (beerreview.user == current_user) || (current_user.admin?) %>
									    <%= link_to "Edit", edit_restaurant_beer_review_path(@restaurant, beerreview) %>
									    <%= link_to "Delete", restaurant_beer_review_path(@restaurant, beerreview), method: :delete %>
									  <% end %>
									<% end %>
								</div>
							</td>
							<td>
								<div class="star-rating" data-score= <%= beerreview.rating %> ></div>
								<p><%= h(beerreview.comments).gsub(/\n/, '<br />').html_safe %></p>
							</td>
						</tr>
					<% end %>
				</tbody>
			</table>
		<% end %>
	</div>
</div>

<script>
	$('.star-rating').raty({path: "https://s3.amazonaws.com/beermeduncan/rating/",
		readOnly: true,
		score: function() {
			return $(this).attr('data-score');
		}
	});
</script>